bot_bot:
  avs_links: |
    Ask `@`AVS-Expert
    Links:
    http://avisynth.nl/index.php/Main_Page
    https://en.wikipedia.org/wiki/AviSynth
    http://www.avs-plus.net/
    https://iamscum.wordpress.com/encoding-stuff/
  vs_links: |
    Ask `@`VS-Expert
    Links:
    http://www.vapoursynth.com/doc/avisynthcomp.html
    https://github.com/vapoursynth/vapoursynth
    https://kageru.moe/
    https://iamscum.wordpress.com/encoding-stuff/
  yuuno_links: |
    Ask `@`VS-Expert
    Links:
    https://pypi.python.org/pypi/yuuno
    https://github.com/stuxcrystal/yuuno
    https://myanimelist.net/character/32939/Arashiko_Yuuno
  x264_links: |
    Ask `#`encode-autism
    Links:
    https://dewikipedia.org/wiki/X264
    https://en.wikibooks.org/wiki/MeGUI/x264_Settings
    http://x264.janhum.alfahosting.org/fullhelp.txt
    https://kageru.moe/
    https://iamscum.wordpress.com/encoding-stuff/
  getnative_links: |
    Ask `#`encode-autism
    Bot:
    You can test getnative with the bot.
    For more information use ">>getnative --help"

    Links:
    https://github.com/Infiziert90/getnative (standalone)
    https://ddl.kageru.moe/kbz12.pdf (WIP)
  member_join: |
    __**English**__
    Hello, please choose your language (only one of them):
    **>>eng** for English
    **>>ger** for German
    Please note that you'll get kicked after 30 minutes and that you won’t have access to most channels without being in one of the two groups.

    __**Deutsch:**__
    Hallo, bitte wähle deine Sprache (nur eine davon):
    **>>eng** für Englisch
    **>>ger** für Deutsch
    Beachte, dass du nach 30 Minuten gekickt wirst und nicht alle Channel sehen kannst, ohne in einer der beiden Gruppen zu sein.
  command_overview: |
    __**English**__
    Commands you can use in this channel to get permissions to view the following channels/categories:

    #public_eng, "Basic" (#asian_content, #games etc.), "Releases", "Voice" | **>>eng**
    #public_jap | **>>role jap**
    "Fansubbing Talk" (#encode-autism etc.) | **>>role subs**
    "NSFW" (#nsfw-anime_manga etc.) | **>>role nsfw**
    #nsfl-anime-manga_gore | **>>role nsfl**
    "Trash" (#logs etc.) | **>>role special**
    "Archive" (Alte read-only Channel) | **>>role archive**

    For example: **>>role subs**


    __**Deutsch**__
    Befehle, die du in diesem Channel nutzen kannst, um die folgenden Channel/Kategorien zu sehen:

    #public_ger, "Basic" (#asian_content, #games etc.), "Releases", "Voice" | **>>ger**
    #public_jap | **>>role jap**
    "Fansubbing Talk" (#encode-autism etc.) | **>>role subs**
    "NSFW" (#nsfw-anime_manga etc.) | **>>role nsfw**
    #nsfl-anime-manga_gore | **>>role nsfl**
    "Trash" (#logs etc.) | **>>role special**
    "Archive" (Alte read-only Channel) | **>>role archive**

    Als Beispiel: **>>role subs**
  help_message: |
    __**Public link**__
    https://discord.gg/V5vaWwr

    If you need any help, write "@Support" with your request in #welcome channel.
    Sofern du irgendwelche Hilfe brauchst, schreib "@Support" mit deinem Anliegen im #welcome Channel.
